
import javax.swing.JFrame;

/*
 * SettingsJFrame.java
 *
 * Created on April 2, 2010, 12:15 AM
 */



/**
 *
 * @author  Dev
 */
public class SettingsJFrame extends javax.swing.JFrame {
    
    /** Creates new form SettingsJFrame */
    public SettingsJFrame() {
        initComponents();
        
        
        if(Welcome.win.tagdebug==true){
            ondebugjRadioButton.setSelected(true);
        }else{
            offdebugjRadioButton.setSelected(true);
        }

        
         if(Welcome.win.tagjmf == true){
            jmfjRadioButton.setSelected(true);
        }else{
            sourcedatalinejRadioButton.setSelected(true);
        }         
        
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        okjButton = new javax.swing.JButton();
        canclejButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ondebugjRadioButton = new javax.swing.JRadioButton();
        offdebugjRadioButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jmfjRadioButton = new javax.swing.JRadioButton();
        sourcedatalinejRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(null);

        okjButton.setText("Ok");
        okjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okjButtonActionPerformed(evt);
            }
        });
        okjButton.setBounds(150, 150, 90, 23);
        jLayeredPane1.add(okjButton, new Integer(3));

        canclejButton.setText("Cancel");
        canclejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canclejButtonActionPerformed(evt);
            }
        });
        canclejButton.setBounds(270, 150, 80, 23);
        jLayeredPane1.add(canclejButton, new Integer(3));

        jLabel1.setText("Debugging : ");
        jLabel1.setBounds(40, 20, 70, 20);
        jLayeredPane1.add(jLabel1, new Integer(2));

        buttonGroup1.add(ondebugjRadioButton);
        ondebugjRadioButton.setText("On");
        ondebugjRadioButton.setBounds(130, 20, 70, 23);
        jLayeredPane1.add(ondebugjRadioButton, new Integer(2));

        buttonGroup1.add(offdebugjRadioButton);
        offdebugjRadioButton.setText("Off");
        offdebugjRadioButton.setBounds(210, 20, 90, 23);
        jLayeredPane1.add(offdebugjRadioButton, new Integer(2));
        jSeparator1.setBounds(20, 130, 370, 10);
        jLayeredPane1.add(jSeparator1, new Integer(2));

        jLabel2.setText("Synthesis : ");
        jLabel2.setBounds(40, 60, 70, 20);
        jLayeredPane1.add(jLabel2, new Integer(2));

        buttonGroup2.add(jmfjRadioButton);
        jmfjRadioButton.setText("JMF");
        jmfjRadioButton.setBounds(130, 60, 70, 23);
        jLayeredPane1.add(jmfjRadioButton, new Integer(2));

        buttonGroup2.add(sourcedatalinejRadioButton);
        sourcedatalinejRadioButton.setText("SourceDataLine");
        sourcedatalinejRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourcedatalinejRadioButtonActionPerformed(evt);
            }
        });
        sourcedatalinejRadioButton.setBounds(210, 60, 120, 23);
        jLayeredPane1.add(sourcedatalinejRadioButton, new Integer(2));

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 360, 190);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-373)/2, (screenSize.height-230)/2, 373, 230);
    }// </editor-fold>//GEN-END:initComponents

    private void canclejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canclejButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_canclejButtonActionPerformed

    private void okjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okjButtonActionPerformed
        if(ondebugjRadioButton.isSelected()==true){
            Welcome.win.tagdebug=true;
            Welcome.win.debugWin=new DebugJFrame();
            Welcome.win.debugWin.setVisible(true);
        }else{
            Welcome.win.tagdebug=false;
        }

        
         if(jmfjRadioButton.isSelected()==true){
            Welcome.win.tagjmf=true;
        }else{
            Welcome.win.tagjmf=false;
        }       
        
        this.dispose();
    }//GEN-LAST:event_okjButtonActionPerformed

    private void sourcedatalinejRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourcedatalinejRadioButtonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_sourcedatalinejRadioButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame.setDefaultLookAndFeelDecorated(true);
                new SettingsJFrame().setVisible(true);
                //JFrame.setDefaultLookAndFeelDecorated(true);
                System.out.println("hi setting main");
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton canclejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton jmfjRadioButton;
    private javax.swing.JRadioButton offdebugjRadioButton;
    private javax.swing.JButton okjButton;
    private javax.swing.JRadioButton ondebugjRadioButton;
    private javax.swing.JRadioButton sourcedatalinejRadioButton;
    // End of variables declaration//GEN-END:variables
    
}
